name: Test Current Time Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Time
        id: time
        uses: tdupoiron-github-demo/releasing-actions/actions/current-time@current-time-v2.0.0
      - name: Print Current Time
        run: |
          echo "The current time is ${{ steps.time.outputs.time }}"